spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/spring
  application:
    name: spring-batch-demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_batch
    username: xxx
    password: xxx
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: true
      name:  KafkaToMongoJob #CsvToKafkaJob
  kafka:
    producer:
      bootstrap-servers:
        - localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: mongo-consumer-group
      properties:
        spring.json.trusted.packages: com.demo.spring.batch.organisation.model
    template:
      default-topic: big-organisation
#      transaction-id-prefix: tx-
